services:
  - type: web
    name: searchsim
    runtime: python
    repo: https://github.com/saberzerhoudi/searchsim
    plan: free
    envVars:
      - key: TAVILY_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: BING_API_KEY
        sync: false
    region: oregon
    buildCommand: poetry install
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: src/backend
version: "1"
