user_study:
  id_code: "US-00123"
  topics_path: "/path/to/topics/file.yaml"
  number_of_topics: 10
  timer:
    enabled: true
    duration: 60000
  llm_endpoints:
    - url: "https://api.example-llm.com/v1"
      api_key: "YOUR_API_KEY_HERE"
  pre_study_questions:
    enabled: true
    config_path: "/path/to/pre_study_questions.yaml"
  search_engine:
    type: "bing"
    api_key: "YOUR_BING_API_KEY_HERE"

# Additional configurations
study_parameters:
  study_date: "2024-06-15"
  duration_days: 7
  participant_limit: 50
  data_collection:
    anonymize_data: true
    store_responses: true
    response_format: "json"
